# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-12 05:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20161211_1435'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
