# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-27 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20161223_0616'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grades',
        ),
    ]
