# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-27 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_delete_grades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.IntegerField()),
                ('courseID', models.IntegerField()),
                ('letterGrade', models.CharField(max_length=1)),
            ],
        ),
    ]
