# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-08 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_auto_20170321_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Batch'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Student'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Batch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
